In [43]:
import tensorflow as tf

In [44]:
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [45]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [46]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis

In [47]:
#hypothesis
hypothesis = tf.matmul(X, W) + b

# Loss function

In [48]:
#simplified loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Gradient Descent

In [49]:
#Gradient Descent to minimize w
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Train the model

In [50]:
#Launch the graph in a session. Train the model
sess = tf.Session()
sess.run(tf.global_variables_initializer()) #initialize global varaibles at first

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction: ", hy_val)

0 Cost:  33356.82 
Prediction:  [[-13.577885 ]
 [ -8.049524 ]
 [-12.060511 ]
 [-13.530748 ]
 [ -3.9779415]]
10 Cost:  4.7636166 
Prediction:  [[147.98433]
 [186.12102]
 [179.26695]
 [194.81912]
 [144.12225]]
20 Cost:  4.435293 
Prediction:  [[148.48117]
 [186.70302]
 [179.8483 ]
 [195.45128]
 [144.56319]]
30 Cost:  4.4123983 
Prediction:  [[148.49066]
 [186.69931]
 [179.8525 ]
 [195.45491]
 [144.55734]]
40 Cost:  4.3896265 
Prediction:  [[148.49866]
 [186.69383]
 [179.85497]
 [195.4567 ]
 [144.55019]]
50 Cost:  4.366972 
Prediction:  [[148.50662]
 [186.68835]
 [179.85739]
 [195.45844]
 [144.54303]]
60 Cost:  4.3445177 
Prediction:  [[148.51456]
 [186.68295]
 [179.85983]
 [195.46017]
 [144.53592]]
70 Cost:  4.322104 
Prediction:  [[148.52249]
 [186.67752]
 [179.86227]
 [195.46191]
 [144.52881]]
80 Cost:  4.2998247 
Prediction:  [[148.5304 ]
 [186.67209]
 [179.8647 ]
 [195.46365]
 [144.52173]]
90 Cost:  4.2776737 
Prediction:  [[148.53827]
 [186.66669]
 [179.8671 ]
 [195.46538]
 [144.514

960 Cost:  2.7453938 
Prediction:  [[149.14833]
 [186.24866]
 [180.05424]
 [195.59886]
 [143.96773]]
970 Cost:  2.7316525 
Prediction:  [[149.15454]
 [186.24442]
 [180.05617]
 [195.6002 ]
 [143.96216]]
980 Cost:  2.717979 
Prediction:  [[149.16074]
 [186.24016]
 [180.05806]
 [195.60156]
 [143.95662]]
990 Cost:  2.7043672 
Prediction:  [[149.16692]
 [186.23592]
 [180.05995]
 [195.60292]
 [143.95108]]
1000 Cost:  2.6908386 
Prediction:  [[149.17308]
 [186.2317 ]
 [180.06184]
 [195.60426]
 [143.94556]]
1010 Cost:  2.6773853 
Prediction:  [[149.17923]
 [186.2275 ]
 [180.06372]
 [195.60562]
 [143.94006]]
1020 Cost:  2.66402 
Prediction:  [[149.18533]
 [186.2233 ]
 [180.0656 ]
 [195.60695]
 [143.93456]]
1030 Cost:  2.6507246 
Prediction:  [[149.19145]
 [186.21913]
 [180.06749]
 [195.60828]
 [143.9291 ]]
1040 Cost:  2.6374667 
Prediction:  [[149.19756]
 [186.21494]
 [180.06935]
 [195.6096 ]
 [143.92363]]
1050 Cost:  2.6242917 
Prediction:  [[149.20363]
 [186.21077]
 [180.07123]
 [195.61095]
 

1990 Cost:  1.6572735 
Prediction:  [[149.70741]
 [185.86563]
 [180.22581]
 [195.72075]
 [143.46701]]
2000 Cost:  1.6494033 
Prediction:  [[149.71211]
 [185.86241]
 [180.22725]
 [195.72177]
 [143.4628 ]]


# Data loading

In [51]:
import os
import numpy as np
os.chdir("C:/Users/snuist/Desktop/Git/study/deeplearning")

In [52]:
tf.set_random_seed(777) #for reproductibility

In [53]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
xy

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [54]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [55]:
print(x_data.shape, len(x_data))
print(y_data.shape)

(25, 3) 25
(25, 1)


In [56]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

w = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [57]:
#hypothesis
hypothesis = tf.matmul(X, W) + b

In [58]:
#loss
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [60]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [61]:
sess = tf.Session()

In [62]:
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict = {X: x_data, Y: y_data})
    if step % 10 == 0 :
        print(step, "Cost: ", cost_val, "\nprediction:\n", hy_val)

0 Cost:  30851.463 
prediction:
 [[-15.00261 ]
 [ -9.47425 ]
 [-13.485236]
 [-14.955474]
 [ -5.402667]
 [ -4.441759]
 [-14.803121]
 [-16.028572]
 [ -7.742694]
 [ -7.71276 ]
 [-11.446431]
 [ -7.95144 ]
 [-13.199981]
 [-10.136487]
 [-13.709943]
 [-10.790862]
 [ -6.672065]
 [-19.452522]
 [-13.862256]
 [-13.624169]
 [-15.603103]
 [-10.03678 ]
 [-15.533929]
 [-13.654742]
 [-10.759612]]
10 Cost:  30.018894 
prediction:
 [[148.93501]
 [187.54901]
 [180.65207]
 [196.4802 ]
 [144.85156]
 [106.34118]
 [143.47601]
 [101.32737]
 [176.39276]
 [162.85208]
 [141.03741]
 [142.39645]
 [187.36491]
 [156.58293]
 [145.29514]
 [189.1479 ]
 [152.09517]
 [170.5047 ]
 [177.34909]
 [157.46696]
 [170.00027]
 [174.80367]
 [161.42397]
 [151.62016]
 [193.43195]]
20 Cost:  28.43006 
prediction:
 [[150.07228 ]
 [188.90099 ]
 [181.99144 ]
 [197.9444  ]
 [145.8744  ]
 [107.102104]
 [144.58447 ]
 [102.16695 ]
 [177.6596  ]
 [164.03644 ]
 [142.09523 ]
 [143.43504 ]
 [188.74268 ]
 [157.71928 ]
 [146.40709 ]
 [190.52652 ]

510 Cost:  23.36718 
prediction:
 [[150.30505]
 [188.47852]
 [181.9164 ]
 [198.11366]
 [145.17061]
 [106.88892]
 [145.28206]
 [103.50288]
 [177.40884]
 [164.29665]
 [142.3    ]
 [143.42348]
 [188.39435]
 [157.02187]
 [147.0308 ]
 [190.40242]
 [151.97842]
 [173.00072]
 [178.40005]
 [158.53174]
 [171.92374]
 [175.97273]
 [163.24532]
 [152.36482]
 [194.3861 ]]
520 Cost:  23.276867 
prediction:
 [[150.30954]
 [188.47015]
 [181.91486]
 [198.11671]
 [145.1569 ]
 [106.88451]
 [145.29523]
 [103.52826]
 [177.40361]
 [164.301  ]
 [142.30373]
 [143.4229 ]
 [188.38765]
 [157.00859]
 [147.04251]
 [190.39972]
 [151.95576]
 [173.0227 ]
 [178.39505]
 [158.5296 ]
 [171.93552]
 [175.97038]
 [163.25638]
 [152.3576 ]
 [194.37735]]
530 Cost:  23.187057 
prediction:
 [[150.31404 ]
 [188.4618  ]
 [181.91335 ]
 [198.11977 ]
 [145.14326 ]
 [106.880104]
 [145.30836 ]
 [103.553604]
 [177.39839 ]
 [164.30534 ]
 [142.30748 ]
 [143.42232 ]
 [188.381   ]
 [156.99538 ]
 [147.05418 ]
 [190.39702 ]
 [151.9332  ]
 [173.

1010 Cost:  19.38677 
prediction:
 [[150.5246  ]
 [188.08218 ]
 [181.84816 ]
 [198.25766 ]
 [144.52419 ]
 [106.67242 ]
 [145.90022 ]
 [104.694115]
 [177.1523  ]
 [164.48291 ]
 [142.47438 ]
 [143.38794 ]
 [188.08739 ]
 [156.40858 ]
 [147.57741 ]
 [190.26976 ]
 [150.92378 ]
 [174.03378 ]
 [178.17432 ]
 [158.44101 ]
 [172.47603 ]
 [175.85692 ]
 [163.76546 ]
 [152.04263 ]
 [193.97536 ]]
1020 Cost:  19.3173 
prediction:
 [[150.52887]
 [188.07468]
 [181.84695]
 [198.26036]
 [144.51201]
 [106.66818]
 [145.91179]
 [104.71639]
 [177.14728]
 [164.48602]
 [142.47762]
 [143.3871 ]
 [188.08179]
 [156.3973 ]
 [147.58755]
 [190.26717]
 [150.9042 ]
 [174.05312]
 [178.17027]
 [158.4395 ]
 [172.48633]
 [175.85463]
 [163.7752 ]
 [152.03691]
 [193.96768]]
1030 Cost:  19.24821 
prediction:
 [[150.53313 ]
 [188.0672  ]
 [181.84573 ]
 [198.26306 ]
 [144.49986 ]
 [106.66395 ]
 [145.92331 ]
 [104.738594]
 [177.14224 ]
 [164.4891  ]
 [142.48085 ]
 [143.38626 ]
 [188.0762  ]
 [156.38603 ]
 [147.5977  ]
 [190.264

1510 Cost:  16.321537 
prediction:
 [[150.73195 ]
 [187.72691 ]
 [181.7943  ]
 [198.38518 ]
 [143.94942 ]
 [106.465614]
 [146.44255 ]
 [105.738754]
 [176.9077  ]
 [164.61415 ]
 [142.62535 ]
 [143.34157 ]
 [187.82936 ]
 [155.88586 ]
 [148.05257 ]
 [190.14293 ]
 [150.01175 ]
 [174.9426  ]
 [177.99174 ]
 [158.37701 ]
 [172.95885 ]
 [175.74461 ]
 [164.22383 ]
 [151.7867  ]
 [193.61366 ]]
1520 Cost:  16.267994 
prediction:
 [[150.73596]
 [187.7202 ]
 [181.79335]
 [198.38756]
 [143.93858]
 [106.4616 ]
 [146.4527 ]
 [105.75828]
 [176.90295]
 [164.61632]
 [142.62816]
 [143.34056]
 [187.82463]
 [155.87622]
 [148.06142]
 [190.14046]
 [149.99481]
 [174.95961]
 [177.98846]
 [158.37596]
 [172.96785]
 [175.74242]
 [164.23242]
 [151.78215]
 [193.60689]]
1530 Cost:  16.214735 
prediction:
 [[150.73997 ]
 [187.7135  ]
 [181.79239 ]
 [198.38995 ]
 [143.9278  ]
 [106.457565]
 [146.4628  ]
 [105.77775 ]
 [176.89821 ]
 [164.61844 ]
 [142.63095 ]
 [143.33954 ]
 [187.81993 ]
 [155.86661 ]
 [148.07022 ]
 [190

In [63]:
#Check the accuracy
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 71, 101]]}))

Your score will be  [[196.50786]]


In [65]:
print("Other score will be ", sess.run(hypothesis, feed_dict={X: [[112, 34, 31]]}))

Other score will be  [[144.31839]]


# Queue Runner

In [73]:
filename_queue = tf.train.string_input_producer(
['data-01-test-score.csv'], shuffle=False, name='filename_queue')

In [74]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [78]:
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [98]:
#collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

In [86]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal(([3,1])), name='weight')
b = tf.Variable(tf.random_normal(([1]), name='bias'))

In [87]:
hypothesis = tf.matmul(X, W) + b

In [88]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [95]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [93]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

## Start populating the filename queue.

In [101]:
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch]) #newly added
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction\n: ", hy_val)

0 Cost:  30.094437 
Prediction
:  [[142.75531]
 [189.38452]
 [159.01329]
 [146.52687]
 [189.59427]
 [154.32715]
 [172.18356]
 [179.74385]
 [159.99773]
 [171.2974 ]]
10 Cost:  29.930706 
Prediction
:  [[142.75871]
 [189.372  ]
 [158.99214]
 [146.54065]
 [189.59338]
 [154.29605]
 [172.20663]
 [179.73193]
 [159.98914]
 [171.31026]]
20 Cost:  29.767944 
Prediction
:  [[142.76205]
 [189.35951]
 [158.97107]
 [146.5544 ]
 [189.59247]
 [154.26503]
 [172.22968]
 [179.72005]
 [159.9806 ]
 [171.32306]]
30 Cost:  29.606298 
Prediction
:  [[142.76541]
 [189.3471 ]
 [158.9501 ]
 [146.56812]
 [189.59157]
 [154.23413]
 [172.25266]
 [179.70824]
 [159.97214]
 [171.33588]]
40 Cost:  29.445612 
Prediction
:  [[142.76872]
 [189.33472]
 [158.92918]
 [146.58177]
 [189.59065]
 [154.20331]
 [172.27557]
 [179.69644]
 [159.96368]
 [171.34862]]
50 Cost:  29.286036 
Prediction
:  [[142.772  ]
 [189.3224 ]
 [158.90836]
 [146.5954 ]
 [189.58972]
 [154.1726 ]
 [172.29843]
 [179.68472]
 [159.9553 ]
 [171.36134]]
60 Co

500 Cost:  23.076544 
Prediction
:  [[142.89552]
 [188.81589]
 [158.04646]
 [147.16786]
 [189.541  ]
 [152.89108]
 [173.26894]
 [179.20842]
 [159.61928]
 [171.89885]]
510 Cost:  22.957981 
Prediction
:  [[142.89778]
 [188.80563]
 [158.02888]
 [147.17972]
 [189.53978]
 [152.8647 ]
 [173.28926]
 [179.19887]
 [159.61266]
 [171.91005]]
520 Cost:  22.840206 
Prediction
:  [[142.90001]
 [188.79543]
 [158.01137]
 [147.19156]
 [189.53856]
 [152.83842]
 [173.30954]
 [179.1894 ]
 [159.6061 ]
 [171.92122]]
530 Cost:  22.723133 
Prediction
:  [[142.9022 ]
 [188.78523]
 [157.99393]
 [147.20335]
 [189.53734]
 [152.81221]
 [173.32976]
 [179.17995]
 [159.59955]
 [171.93236]]
540 Cost:  22.606857 
Prediction
:  [[142.90442]
 [188.7751 ]
 [157.97655]
 [147.2151 ]
 [189.5361 ]
 [152.7861 ]
 [173.34993]
 [179.17055]
 [159.59305]
 [171.94348]]
550 Cost:  22.49128 
Prediction
:  [[142.9066 ]
 [188.76501]
 [157.95923]
 [147.22684]
 [189.53487]
 [152.76007]
 [173.37007]
 [179.1612 ]
 [159.58658]
 [171.95456]]

1020 Cost:  17.814234 
Prediction
:  [[142.98907]
 [188.33305]
 [157.21254]
 [147.74046]
 [189.4721 ]
 [151.62769]
 [174.26048]
 [178.7655 ]
 [159.31819]
 [172.44264]]
1030 Cost:  17.729132 
Prediction
:  [[142.99046]
 [188.32472]
 [157.19801]
 [147.75064]
 [189.4707 ]
 [151.60542]
 [174.2783 ]
 [178.75797]
 [159.31319]
 [172.45238]]
1040 Cost:  17.644522 
Prediction
:  [[142.9918 ]
 [188.31639]
 [157.18352]
 [147.76079]
 [189.46928]
 [151.58322]
 [174.29608]
 [178.75047]
 [159.30821]
 [172.46207]]
1050 Cost:  17.560495 
Prediction
:  [[142.99315]
 [188.30812]
 [157.16907]
 [147.77089]
 [189.46785]
 [151.5611 ]
 [174.3138 ]
 [178.74297]
 [159.30324]
 [172.47173]]
1060 Cost:  17.476946 
Prediction
:  [[142.99449]
 [188.29987]
 [157.1547 ]
 [147.78098]
 [189.46643]
 [151.53905]
 [174.3315 ]
 [178.73552]
 [159.29831]
 [172.48138]]
1070 Cost:  17.393986 
Prediction
:  [[142.9958 ]
 [188.29166]
 [157.14035]
 [147.79103]
 [189.46501]
 [151.51707]
 [174.34912]
 [178.72812]
 [159.29341]
 [172.

1510 Cost:  14.215578 
Prediction
:  [[143.041  ]
 [187.96008]
 [156.55797]
 [148.20544]
 [189.40002]
 [150.6166 ]
 [175.08235]
 [178.43275]
 [159.10182]
 [172.8892 ]]
1520 Cost:  14.153046 
Prediction
:  [[143.04175]
 [187.95319]
 [156.54576]
 [148.21425]
 [189.3985 ]
 [150.59753]
 [175.09808]
 [178.42668]
 [159.09796]
 [172.8977 ]]
1530 Cost:  14.09093 
Prediction
:  [[143.04253]
 [187.94632]
 [156.53362]
 [148.22305]
 [189.397  ]
 [150.57858]
 [175.11378]
 [178.42065]
 [159.09415]
 [172.9062 ]]
1540 Cost:  14.029218 
Prediction
:  [[143.04327]
 [187.93948]
 [156.52151]
 [148.23181]
 [189.39548]
 [150.55966]
 [175.12944]
 [178.41464]
 [159.09035]
 [172.91466]]
1550 Cost:  13.967867 
Prediction
:  [[143.04399]
 [187.93266]
 [156.50943]
 [148.24054]
 [189.39395]
 [150.54083]
 [175.14505]
 [178.40868]
 [159.08656]
 [172.92311]]
1560 Cost:  13.906926 
Prediction
:  [[143.04472]
 [187.92589]
 [156.4974 ]
 [148.24927]
 [189.39246]
 [150.52203]
 [175.16061]
 [178.40271]
 [159.08281]
 [172.9

In [102]:
coord.request_stop()
coord.join(threads)